export type RootStackParamList = {
    Splash: undefined;
    HomeScreen: undefined;
    MangaInfoScreen: { mangaId: string } | undefined;
    SearchScreen: undefined;
    LibraryScreen: undefined;
    DownLoadsScreen: undefined;
    ReaderScreen: { chapterId: string; mangaId: string; chapterNum: string } | undefined;
    SettingsScreen: undefined;
    ReadingStatsScreen: undefined;
    RecentlyUpdated: undefined;
    RecentlyReadScreen: undefined;
    FeedBackHome: { username?: string; securityLevel?: number } | undefined;
    FileReport: undefined;
    AdminScreen: undefined;
    LoginScreen: undefined;
    UserAccount: undefined;
    CreateAccount: undefined;
    ForgotCredentials: undefined;
    ChooseProfileIcon: undefined;
    LeaveRating: undefined;
    LeaveReview: undefined;
};
